export { MODULE_REGISTRY, renderSections, type ModuleCommonProps } from "./registry";
export { themeStyle, FONT_VAR_MAP, uc } from "./theme/theme";
export * from "./primitives";
export * from "./footer";
export { heroDefaults } from "./modules/HeroStorefront";
export { catalogDefaults } from "./modules/ProductCatalogWA";
export { promoDefaults } from "./modules/PromoBanner";
export { hoursDefaults } from "./modules/OperatingHoursMap";
export { reviewsDefaults } from "./modules/SocialProofReviews";
export { channelsDefaults } from "./modules/ChannelMarketplace";
export { faqDefaults } from "./modules/FaqAccordion";
export { contactDefaults } from "./modules/ContactDirect";
export { richTextDefaults } from "./modules/RichTextBlock";
export { galleryDefaults } from "./modules/GalleryGrid";
export { pricingDefaults } from "./modules/ServicePricingTable";
export { trustDefaults } from "./modules/TrustBadgesStrip";
export { stepsDefaults } from "./modules/StepHowToOrder";
